### ISSUE TITLE
Render Spectre markup in log messages

### ISSUE THREAD

**Issue by caesay** [verticalsoftware/vertical-spectreconsolelogger#31]
Becuase of this line: https://github.com/verticalsoftware/vertical-spectreconsolelogger/blob/d0913f70426d4d47c9c91e574b3eff371720daab/src/Output/WriteBufferExtensions.cs#L64

It's not possible to pass through Spectre markup in log messages when building rich console applications. It would be nice if this was configurable.

**Comment by daningalla** [comment]
@caesay - this would not be hard to implement as a configuration, however I feel compelled to discuss. The pure intention of the library is to keep Spectre markup _out_ of logging statements. Can you help me understand the use case of leveraging an abstraction over `IAnsiConsole` instead of writing directly to it?

**Comment by caesay** [comment]
I am working on [velopack](https://github.com/velopack/velopack), and all of the core libraries only take a dependency on msft logging, and try to avoid directly using spectre references at all costs, but they do also use spectre markup in the log messages themselves. This feels to me like a good balance, because I can then swap out the logging pipeline to a non-Spectre one without things breaking, and even strip out the markup. Some of the libraries are even intended for use in consuming applications, so having a very high level general abstraction like msft ilogger is important.

I came across this library because there are not many great ways to use Spectre with ILogger. Having tried pretty much everything I can find, most libraries trying to do this are riddled with bugs - and indeed I ran into a few using this project related to using Spectre progress bars in conjunction with logging, so I ended up just writing my own simple Serilog Sink instead - as it seems to solve all the bugs and keeps things really simple. 

If you don't think this suggestion would be useful to others, feel free to close this issue.

**Comment by daningalla** [comment]
I will experiment with adding a property called `PreserveOriginalFormatStrings` (or similar) in the profile object and see how the tests fare. 

Thanks for the input, always appreciated.

**Comment by GuillaumeGuerra** [comment]
Hi 🙌 

Thanks a lot for the library, very helpful !!
Indeed, I would appreciate to have an option to support spectre markup out of the box

As said by @caesay, it would be helpful to write formatted logs into the regular ILogger, without applying complex formatting setup, leveraging on the very simple spectre built-in markup language
However, as you said it will generate noise in the other registered loggers, if any, but it's a deployment choice 

Thanks again !

**Comment by daningalla** [comment]
@caesay @GuillaumeGuerra  - please see the referenced commit, new dev package will be pushing

**Comment by GuillaumeGuerra** [comment]
will check it out asap

thanks alot ! @daningalla 🙏

**Comment by GuillaumeGuerra** [comment]
works like a charm 👍
much appreciated @daningalla !

**Comment by daningalla** [comment]
Thanks for using @GuillaumeGuerra!
