### ISSUE TITLE
Hierarchy support for minimum log level categories

### ISSUE THREAD

**Issue by Sam13** [verticalsoftware/vertical-spectreconsolelogger#35]
```csharp
  configure.AddSpectreConsole(options =>
            {
                options.SetMinimumLevel(LogLevel.Debug);
                options.SetMinimumLevel("Microsoft.Hosting", LogLevel.Warning);
            });
```
will still log categories such as `Microsoft.Hosting.Lifetime` and `Microsoft.Hosting.Internal.Host` in log levels information and debug.

Minimum levels can only be configured for exact category name.
Adding support for hierarchy of category names as in other logging providers would be nice.

**Comment by daningalla** [comment]
@Sam13 - `vertical-spectreconsolelogger.0.10.1-dev.20241130.34.nupkg` up

**Comment by Sam13** [comment]
@daningalla 
Works good.
Thanks a lot for the quick implementation!

**Comment by daningalla** [comment]
Thanks for trying it out! Cheers
